### ISSUE TITLE
Proposal: Joint Discourse forum for asynchronous communication

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#14]
Addressing #9

Let’s use Discourse. It's nice and has a bunch of features.

We should consolidate the community async communication to a single place. We share users, dependencies, and sometimes bugs. I think there are some obvious synergies here.

We should make this available for non-core packages. E.g. allow ecosystem packages to use this for their async non-issue communication channel. This is good for broadening the community and increasing visibility of ecosystem packages.

## Challenges

* We should get developers to post here more. How?
    * Make some processes run through this? Force checking?
* We need to figure out how to structure it

**Comment by adamgayoso** [comment]
Related to #18 I could also see the opposite -- relying mostly on discourse. Stan does this for example

https://discourse.mc-stan.org/c/stan-governance/41

We could pair this with discord for live events, informal chat for core members to organize things quickly.

**Comment by grst** [comment]
> Related to https://github.com/scverse/governance/issues/18 I could also see the opposite -- relying mostly on discourse. Stan does this for example

I could also see that - In general I'm a big fan of asynchronous communication, as it tends to be more structured and better thought of. 

On the other hand I can see how great the instant-messaging slack workspace works for community building in nf-core. I think it significantly reduces the barrier of getting involved and getting in touch with people.

**Comment by adamgayoso** [comment]
> On the other hand I can see how great the instant-messaging slack workspace works for community building in nf-core. I think it significantly reduces the barrier of getting involved and getting in touch with people.

This I understand, though unless I'm unaware, there doesn't seem to be a lot of activity in the CZI science slack or even really the scanpy slack (perhaps restricted to private messages, which I'm proposing we would have with discourse + discord model).

Also aren't discourse messages/questions google searchable?  That seems like a huge advantage.

Would be great to talk out even what we think our community is in the next meeting so we can better tune our choices to that.

**Comment by grst** [comment]
> Would be great to talk out even what we think our community is in the next meeting so we can better tune our choices to that.

:100:, because ultimately the whole communication channels discussion boils down to that people prefer to use what they are used to. 

In my case it's Slack and GitHub, while I only used discourse when I had to. For our community, I don't know, but it's most likely not Zulip.

**Comment by ivirshup** [comment]
> Would be great to talk out even what we think our community is in the next meeting so we can better tune our choices to that.

Wolfgang Huber had some advice for us here. That our community has two large groups, analysts and developers. He recommended looking at this bioconductor paper for more on this: https://www.nature.com/articles/nmeth.3252

I think Discourse makes a ton of sense for analysts. I think a lot of their interaction with the community will be question and answer + finding docs. The people they collaborate with are most likely external to our community.

I think chat makes a ton of sense for developers. Synchronous chat is a good place to network and organize. Also, being an active community member in a chat app does take more time. I wouldn't expect most analysts to be as invested in the ecosystem and community as a developer would.

**Comment by ivirshup** [comment]
> as much development talk to discourse 

I think this is an interesting case, because we already have github for a lot of this. `image.sc` seems to do a lot with their discourse, we could ask them for more info

**Comment by ivirshup** [comment]
:+1:

I was also thinking:

* Proposals for new packages
* Proposals/ discussion of cross package features

**Comment by adamgayoso** [comment]
Right, and in that case, GitHub is only used to track issues that will concretely turn into PRs

**Comment by adamgayoso** [comment]
Closing due to #23
