### ISSUE TITLE
Proposal: Slack for org chat

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#15]
Addressing #9

The current scanpy Slack, but someone else pays for it.

* Helmholtz either can’t or won’t apply for reduced slack pricing. The bill is currently over 1000 euro a year, and thats without making it open.
* We would get an 85% discount by having slack paid for by an organization who will get the discount. This could be saverse with a numfocus membership, but we need to get that set up.

Pros:

* Very easy
* Everyone is familiar with slack
* We don’t lose any history (any migration path will lose all private history)

Cons:

* Not cheap. It won’t be expensive, but it is a continuous drag on resources
* Some other org needs to volunteer

**Comment by Zethson** [comment]
Simply too expensive imo. The nf-core slack is more than 2300 people. Now we will start smaller, but the more we grow the more ridiculous this expensive becomes.
Alternative would only be to ignore the 10k messaging limit, but IMO history is very important.

**Comment by grst** [comment]
What about [mattermost](https://mattermost.com/)? 
Works pretty much the same as slack and can either be self-hosted (open source edition), or there's a managed version for 149$/year, independent of the number of users.

**Comment by Zethson** [comment]
> What about [mattermost](https://mattermost.com/)? Works pretty much the same as slack and can either be self-hosted (open source edition), or there's a managed version for 149$/year, independent of the number of users.

I like it :) Theislab is actually running on mattermost.

But had the impression that @ivirshup was never the biggest fan of it.

**Comment by ivirshup** [comment]
Maybe it's good with threading. Most of the labs mattermost channels become pretty useless with the "all messages go to main but we still call it threads". So many conversations get confused or just drop.

Also, didn't Fabian say something about us switching to slack yesterday?

**Comment by Zethson** [comment]
> Maybe it's good with threading. Most of the labs mattermost channels become pretty useless with the "all messages go to main but we still call it threads". So many conversations get confused or just drop.
> 
> Also, didn't Fabian say something about us switching to slack yesterday?

Yeah, I also prefer the Slacklike threads. 
I didn't hear or read him saying that.

**Comment by ivirshup** [comment]
> But I can live with the MM ones.

I think you're setting the bar too low 😉  

> I didn't hear or read him saying that.

[Here](https://mattermost.helmholtz-muenchen.de/ml/pl/f5yyc5nkzt8cxjrpw9183fdofh)

**Comment by Zethson** [comment]
> > But I can live with the MM ones.
> 
> I think you're setting the bar too low 😉
> 
> > I didn't hear or read him saying that.
> 
> [Here](https://mattermost.helmholtz-muenchen.de/ml/pl/f5yyc5nkzt8cxjrpw9183fdofh)

I read that but had the impression that he meant the Scanpy Slack or just mixed up some words. This kinda stuff would be discussed more broadly.

**Comment by ivirshup** [comment]
On the topic of mattermost, can one turn on a "recent threads" or "recent DMs" feed? Been realizing I use those a lot in slack.

**Comment by Zethson** [comment]
> On the topic of mattermost, can one turn on a "recent threads" or "recent DMs" feed? Been realizing I use those a lot in slack.

I don't know TBH.

**Comment by adamgayoso** [comment]
Closing due to agreement to go for #16
