### ISSUE TITLE
Proposal: Zulip for org chat

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#16]
Let's use [Zulip](https://zulip.com) for org chat (addressing #9).

Zulip is an open source chat app which seems to be gaining popularity among OSS projects.

It's currently used by:

* [rust](https://zulip.com/case-studies/rust/)
* [julia](https://julialang.zulipchat.com/)
* [napari](https://napari.zulipchat.com)
* [imagesc](https://imagesc.zulipchat.com/) – this one seems new, but I’ve heard they like it!

I think I really like it's threading model, which is a bit unusual. Basically channels have threads. Threads have names. Under the channel you can see which threads were recently active. I think this makes it much easier to catch up and continue existing conversations. [Other people think this too](https://news.ycombinator.com/item?id=27149123). I think this solves the problem of opening tons of little channels that get used a couple times, but always take up space in the sidebar.

## Pros

* Free for open source (also not venture funded, so less likely to dump this when they need a profit?)
* [Very nice threading model](https://zulip.com/help/streams-and-topics)
* Seems to have [decent values](https://blog.zulip.com/2021/11/12/why-not-blockchain/)
* Login with github (don’t need to make a new account), upcoming release has many more SSO integrations
* [Good with markdown](https://zulip.com/help/format-your-message-using-markdown): Syntax highlighting, latex support, message preview, universal times, etc.
* Software developers + [open source](https://zulip.com/for/open-source/) are the target market
* Integration with matrix rooms/ mailing-list like email.
* [Actively developed](https://zulip.readthedocs.io/en/latest/overview/changelog.html) – the [open streams feature](https://github.com/zulip/zulip/issues/4817#issuecomment-985071111) in particular is appealing
* [Moderations tools](https://chat.zulip.org/help/moderating-open-organizations) – including new user restrictions and stream specific rules

## Cons

* Kinda ugly (scale up the UI with `⌘`-`+` and it's much much better)
* Less commonly used (but that's what [RamBox](https://rambox.app) is for)
* Can't customize the look much

---------------

I'd personally prefer this to Slack.

<details>
<summary> Old version </summary>

Let's use [Zulip](https://zulip.com) for org chat (addressing #9).

Zulip is an open source chat app which seems to be gaining popularity among OSS projects.

It's currently used by:

* [rust](https://zulip.com/case-studies/rust/)
* [julia](https://julialang.zulipchat.com/)
* [napari](https://napari.zulipchat.com)
* [imagesc](https://imagesc.zulipchat.com/) – but this one seems new

I think I really like it's threading model, which is a bit unusual. Basically channels have threads. Threads have names. Under the channel you can see which threads were recently active. I think this makes it much easier to catch up and continue existing conversations. [Other people think this too](https://news.ycombinator.com/item?id=27149123). I think this solves the problem of opening tons of little channels that get used a couple times, but always take up space in the sidebar.

## Pros

* Free for open source (also not venture funded, so less likely to dump this when they need a profit?)
* Nice threading model
* Seems to have [decent values](https://blog.zulip.com/2021/11/12/why-not-blockchain/)
* Login with github
* syntax highlighting and latex support

## Cons

* Kinda ugly (scale up the UI with `⌘`-`+` and it's much much better)
* Less commonly used (but that's what [RamBox](https://rambox.app) is for)
* Can't customize the look much

---------------

I'd personally prefer this to Slack.

</details>

**Comment by grst** [comment]
I like this a lot! It seems to have all the advantages of slack, but none of its downsides!

**Comment by Zethson** [comment]
Maybe we could even get it for free if Fabian asks TUM: https://zulip.com/case-studies/tum/

**Comment by grst** [comment]
Reaseach & open source projects get it for free anyway.

**Comment by Zethson** [comment]
Ah yeah, right. I forgot :facepalm:

**Comment by ivirshup** [comment]
Updated this a bit after seeing @gtca's nice write up for discord #21.

**Comment by adamgayoso** [comment]
Who funds Zulip? A potential con is that it can spontaneously shut down (see [Quill](https://hypebeast.com/2021/12/twitter-quill-acquisiton-messaging-announcement)). This is much less likely to happen to discord if I had to guess.

**Comment by ivirshup** [comment]
@adamgayoso they had a blog post noting quill recently: https://blog.zulip.com/2021/12/17/why-zulip-will-stand-the-test-of-time/

No venture funding, currently running off NSF SBIR loan and revenue.

**Comment by adamgayoso** [comment]
> No venture funding, currently running off NSF SBIR loan and revenue.

That could be good or bad

**Comment by giovp** [comment]
zulip seems pretty active in imagesc and napari community, would probably prefer this over discord although it has less functionality (e.g. discord has group video chats out of the box which is nice). Please anything but teams.

**Comment by adamgayoso** [comment]
>  When the company owns itself, people who started the company are in charge. When venture funded, the people ultimately in control are involved for a profit.

Eh, we are all talking here on GitHub right now (owned by Microsoft) and don't have any concerns about it's long term stability. Discord has like 300 million registered users.

**Comment by ivirshup** [comment]
One other nice feature from Zulip, [you can transfer messages to other threads](https://zulip.com/help/move-content-to-another-topic). So when a thread starts meandering (as they do), you can split it off and keep things organized for everyone who comes by later.

-----------------

> Eh, we are all talking here on GitHub right now (owned by Microsoft)

I don't think being owned by Microsoft is too similar to being venture backed.
