### ISSUE TITLE
Proposal: Gitter

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#17]
Gitter (from @adamgayoso)

**Pros**

- Free
- Channels (rooms)
- Threads
- Decent search
- Private messaging
- Can be accessed from Element
- Latex, github-flavored markdown
- Integrations with github, discourse
- Gitter desktop/mobile apps
- Simplicity means it's not ideal for more involved discussion such as Q+A (leave to discourse)

**Cons**

- A little less snappy and intuitive than slack
- Slack search better

> Clicking the channel name takes you to a github repositrory

This is only because I associated that room with a github repo, this is optional

_Originally posted by @adamgayoso in https://github.com/scverse/governance/issues/9#issuecomment-1029278897_

**Comment by ivirshup** [comment]
Split this out because I like threads.

## Additional pros

* "Federated", so you don't have separate PMs with people across separate projects
  * But also, the ability to block bad actors from the community seems valuable.

## Additional cons

* User settings is limited to dark mode vs light mode (wanted to turn on email notifications for missed messages, no options for this)
* [The docs](https://gitlab.com/gitterHQ/webapp/tree/develop/docs#documentation)
* Very limited moderation tooling. May have code of conduct enforceability considerations.
* A number of settings (like removing or renaming org) require emailing the devs to change, which is worrying because it looks like there is only one dev

## Questions

* Are you in any gitter workspaces that use many rooms? All the channels I'd joined recently have at most two.
Can you allow users to create channels in a workspace?
* Do you think there is a reason most gitter channels
* Are there roles within an Org other than admin?

--------------

> Simplicity means it's not ideal for more involved discussion such as Q+A (leave to discourse)

This channel is also meant for dev chat, where I think involved realtime discussion is quite useful. Also useful for hackathons/ live events.

**Comment by ivirshup** [comment]
@adamgayoso, I think that the inability to ban a bad actor from DMing community members (or even mass messaging them through private channels) is disqualifying from a CoC enforcement perspective.

What do you think?

**Comment by adamgayoso** [comment]
agree, discord seems better now that I'm looking into it
