### ISSUE TITLE
Proposal: No asynchronous messaging platform

### ISSUE THREAD

**Issue by grst** [scverse/governance#18]
I agree that we need a place to drag help requests and general questions away from github issues. 
But having a decently structured chatroom (#16, #15) already solves this problem. Especially the zulip topics appear to allow additional structuring of conversations. 

## Pros

 * Simple for users. It's already difficult enough to communicate to users the distinction between issues and non-issues. The possibility to choose the correct out of three makes it even more difficult. 
 * Simple for core-members. If I remember having had a certain conversation, I only need to search in two places for it. 
 * It seems to work reasonably well for nf-core with 50 subprojects and >2000 users. I'm quite active in that community and never missed an additional communication platform. 

## Cons
 * not discoverable via search engines
 * some posts may get lost in channels with high traffic. zulip seems to address that.

**Comment by ivirshup** [comment]
This does seem interesting. I have been wondering how possible it is for Zulip to bridge the gap fully.

Zulip does have a feature for [making search engine indexible archives](https://zulip.com/help/import-from-slack), but I'm not sure it works great. Each time I've searched for something fairly specific it's still a few results down.

If we choose Zulip as a chat app, maybe we could try it out internally before we launch, then decide if we still need an asynchronous option?

**Comment by grst** [comment]
Here's an example of such an archive: 
https://leanprover-community.github.io/archive/

**Comment by Zethson** [comment]
> Here's an example of such an archive: https://leanprover-community.github.io/archive/

This looks surprisingly good TBH. But we would need to enforce a rather strict usage of threads, right?

**Comment by ivirshup** [comment]
> But we would need to enforce a rather strict usage of threads, right?

How so?

I'm not sure you can post a message outside a thread. You may have to start a new thread for there to be messages.

**Comment by Zethson** [comment]
Ah, this I didn't know. Think I need to try Zulip :)

**Comment by adamgayoso** [comment]
> Here's an example of such an archive:
https://leanprover-community.github.io/archive/

This looks kind of ugly no? Will it keep all formatting (latex, markdown)? Is it just for search engine indexing? Also there's something weird about posting on what feels like an instant messaging app without explicitly knowing it will appear on the web publicly (would have to make that very obvious).

**Comment by adamgayoso** [comment]
Following up on this based on conversations in the lab so I don't forget when we meet:

1. There is a lot of slack fatigue
1. Tracking down information on slack is not that easy (especially if it/zulip becomes the main platform for Q+A)
1. The immediate availability on a platform like slack can discourage participation (not easy to track unanswered things)
1. Learning a new platform (like zulip) discourages participation
1. A lot of participants (maybe even the majority) in the community will be individuals seeking help about a package and don't want to download a new thing to ask a handful of questions
1. Forums (e.g., discourse) are a familiar format, are already in use in other scientific projects (Stan, PyTorch, Tensorflow, Pyro, Julia)
1. Our forum has gotten more engagement from the community than our github issues ever did
1. Putting all the packages in one forum will facilitate greater participation

I'd also note that a lot of the coordination of the early progress in this org has been async (github issues), which I'd say is easier to follow than slack -- especially as we are across time zones.

**Comment by adamgayoso** [comment]
Closing based on discussions today, discourse + zulip.
