### ISSUE TITLE
Role of PIs

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#19]
We recognize that the institutions that pay us make this project possible, and want to make sure they get appropriate recognition for this (so that they can continue paying us and people like us). We’re trying to figure out how to do this without implying exclusivity to or ownership by these institutes and labs.

Right now what we have is lab heads who have supported the development of these packages in the "scientific advisors" role. This sounds a lot like "scientific advisory board", which isn't a great fit.

# Questions

* How do we recognize the PIs and institute's that support this work? Do we recognize groups and institutes differently?
* What is the name for this?
* What constitutes a supporting PI? There are groups whose labs contribute many methods to the ecosystem, but don't neccesarily directly support the maintenance of core tools in the ecosystem. These are also important, but maybe there should be a distinction? Is this a possible "scientific advisory board"?

-------------

Subset of #3

**Comment by grst** [comment]
> . We’re trying to figure out how to do this without implying exclusivity to or ownership by these institutes and labs.

In nf-core, every repo has a "Credits" section, which usually states the original authors and their institutions, e.g. [nf-core/rnaseq](https://github.com/nf-core/rnaseq#credits). I think this is a good start.

**Comment by adamgayoso** [comment]
> We recognize that the institutions that pay us make this project possible

Well in our case it's really labs not institutions and by labs I really mean one individual. Therefore, I would propose to ensure that each project in scverse has a representing PI whose role it is to ensure long-term support of the project. In addition, PIs can transfer "ownership" to other PIs in the future. I think it's important to keep in mind that a lot of the projects that will likely join this org are the focal point of a lot of R+D in the PIs lab. 

While there may be the case of one PI representing multiple projects, we can likely figure out how they don't get multiple votes.

It's also possible in the future if the org has independent leadership and funding that the org is responsible for a project, but this seems highly unlikely to me as a scenario.

**Comment by grst** [comment]
> While there may be the case of one PI representing multiple projects, we can likely figure out how they don't get multiple votes.

What kind of things would PIs vote about in the first place? I doubt any of our PIs has the time and interest to vote on any of the technical proposals we are currently discussing. So if there is some "formal" involvement of PIs, then it makes sense IMO to separate technical and strategic topics.

**Comment by Zethson** [comment]
> > While there may be the case of one PI representing multiple projects, we can likely figure out how they don't get multiple votes.
> 
> What kind of things would PIs vote about in the first place? I doubt any of our PIs has the time and interest to vote on any of the technical proposals we are currently discussing. So if there is some "formal" involvement of PIs, then it makes sense IMO to separate technical and strategic topics.

Yeah. Also, if we always involve PIs we will also block ourselves a little bit and decisions will take much longer. We should try to run independently with "just" some high level guidance from the PIs as much as possible IMO.

**Comment by ivirshup** [comment]
> It's also possible in the future if the org has independent leadership and funding that the org is responsible for a project, but this seems highly unlikely to me as a scenario.

Funding for the org directly is a near term goal. I'd like to go for the next round of CZI funding, also looking at plain text group. This funding would be for events, community manager, software developers. I don't think this is mutually exclusive from labs receiving funding for work on scverse packages.

> While there may be the case of one PI representing multiple projects, we can likely figure out how they don't get multiple votes.

I don't think PI's would get votes for any of the things we are deciding right now. IIRC, Oli and Fabian have also specifically expressed not wanting this.

**Comment by adamgayoso** [comment]
> Funding for the org directly is a near term goal. I'd like to go for the next round of CZI funding, also looking at plain text group.

Is someone setting up a non-profit organization?

>  Also, if we always involve PIs we will also block ourselves a little bit and decisions will take much longer. We should try to run independently with "just" some high level guidance from the PIs as much as possible IMO.

I don't see it as constantly needing them, but I guess I was also confused that in the PRs "voting" means voting on technical aspects, where there should also probably be strategic aspects as the PIs will likely support the software longer than any of us.

**Comment by grst** [comment]
> as the PIs will likely support the software longer than any of us.

This is likely not the case for scirpy, though. My PI has currently no interest in putting additional resources into the software. In fact, one motivation of me joining scverse is that it makes it more likely that scirpy doesn't die when I finish my PhD. This is also why I think scverse getting own funding is a good idea.

**Comment by ivirshup** [comment]
Current thinking is we will have:

* "Management Committee" for PIs who are taking an active role in the project, e.g. have positions for people on the core team
* "(Science) Advisory Committee" for  PIs in the broader environment. These would be PIs of labs that have made significant contributions to the ecosystem, but do not necessarily support development of the core packages.

Could also switch out "committee" for "board".

**Comment by Zethson** [comment]
Board might be better because we already have a committee. Might distinguish PIs from us normal dudes better?

**Comment by Zethson** [comment]
Think we can close this now with the new roles definition? Feel free to reopen.
