### ISSUE TITLE
Proposal: Gitter/Matrix for org chat

### ISSUE THREAD

**Issue by ilia-kats** [scverse/governance#20]
Let's use Gitter/Matrix for org chat (addressing #9)

Gitter started out as a chat service for GitHub repositories, but has recently become a client for the Matrix protocol. Matrix is an open, federated chat protocol supporting (among other things) e2e encryption. A user has a home server, but can access rooms (channels) on all servers participating in the federation. Because it's open, there are [many clients](https://matrix.org/clients/) available.

Matrix is used by many open source projects, including:
- [KDE](https://community.kde.org/Matrix) (which runs its own server)
- [Mozilla](https://wiki.mozilla.org/Matrix) (also running its own server)
- [Fedora](https://chat.fedoraproject.org/)

## Pros
- completely open
- federated (people alread on Matrix dont' need an extra account)
- e2e encryption
- many clients available
- [extensive moderation tools](https://matrix.org/docs/guides/moderation)
- many bridges available, including IRC

## Cons
- mods cannot prevent users from sending DMs (individual users can block other users though). However, other rather large communities don't seem to have an issue with this

**Comment by Zethson** [comment]
Big fan of Matrix. However, I always had the experience that even the by far best client (Element) to the Matrix network wasn't really 100% user friendly yet. The required constant verification, especially when new devices are introduced, might be off putting to novice users. 

Or do you see this as a non-issue @ilia-kats ?

**Comment by ilia-kats** [comment]
I don't really have a lot of experience with Element (I try to use native clients over Electon/web-based ones), but I haven't experienced this so far. I guess that is something we should test.

**Comment by ivirshup** [comment]
Reference to previous gitter proposal: #17

**Comment by adamgayoso** [comment]
Closing due to agreement to use zulip
