### ISSUE TITLE
Creating the scverse discourse

### ISSUE THREAD

**Issue by adamgayoso** [scverse/governance#24]
We effectively have two options

## 1. Migrate scanpy discourse to scverse discourse

Pros:

- History
- User base
- It's [free](https://free.discourse.group/) for open source software 

Cons:

- Might not be straightforward to change name to scverse, stuck with `name.discourse.group`
- Can't import other discourse (scvi-tools), see free page linked above, relatedly it's not a dealbreaker to export scvi-tools, but would be nice
- Free plan limited to 50k monthly page views, 5gb storage
- If we outgrow free plan, must move to paid plan

## 2. Start with scvi-tools, change name

Pros:

- Already under an academic discount, thus can upgrade plans easily (to a better paid plan if need be)
- 100k monthly page views, 20gb total storage
- Should be able import scanpy content into this one, but even if we can't, most of Scanpy's topics are unanswered, we can leave the Scanpy one open indefinitely and keep it as a free reference. Can also add a post describing what to do if they are not finding what they want (look in issues of package, look in old scanpy discourse). Within a year the old resources should become mostly irrelevant.

Cons:

- Not free, but payment already handled (~$20 USD/month)
- Lose existing scanpy userbase (though scanpy isn't terribly active), making an account is as easy as having a github/google account anyway.

**Comment by ivirshup** [comment]
Since the scanpy one is already at around ~20% of the page view capacity, I think a discounted paid plan makes sense. Would be happy to migrate over with a name change.
