### ISSUE TITLE
Zulip structure

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#27]
# Channels

## Main channels

- [x] General
- [x] Announce (is this mod only?)
- [x] Random
- [x] Core team (private/ w history)
- [x] Steering council (private w history)

## Optional channels?

- Community
    - [x] New users
        - Where people introduce themselves
    - [ ] Governance
        - For discussion of governance
    - [ ] Social
        - How scverse is represented, twitter, website, etc
    - [ ] Appreciation (Example from Julia](https://julialang.zulipchat.com/#narrow/stream/225583-appreciation)
        - Place to post accolades?
- Analysis topics
    - [x] Genomics
    - [x] Spatial
    - [ ] Datasets
- Packages? 
    - I’ll leave these to the individual maintainers to open. But do we want separate ones?
    - Maybe we could try and group some. Like AnnData + MuData -> data structures?
- Tooling
    - Should we have separate streams for docs and CI, or are those both “repo management”

# Permissions

- [ ] Who wants to be a mod?
- Do we restrict permissions of new users? E.g. have to wait, read something before you can post?
    - I think we don’t do this right away. Let’s revisit after launch. If there is ever a spam issue, lets turn it on.
- [ ] Email
    - So it either it’s publicly visible for everyone or no one.
    - Which? I’d go not visible? Should be easy enough to find for most people?
- Edit message
    - Time limit for editing messages? 
    - Time limit for deleting messages?
    - Can users delete their own messages? (yes? why not)

**Comment by Zethson** [comment]
>  Announce (is this mod only?)

Would suggest, yes.

> Maybe we could try and group some. Like AnnData + MuData -> data structures?

I like this.

> Should we have separate streams for docs and CI, or are those both “repo management”

I'd not create separate streams for those. They should be handled by the respective package. 

> Do we restrict permissions of new users? E.g. have to wait, read something before you can post? 

Big no. 

> So it either it’s publicly visible for everyone or no one.

Can't this be a user choice? People that want it to be displayed enter it and others don't?

> Time limit for editing messages?

No.

> Time limit for deleting messages?
> Can users delete their own messages? (yes? why not)

Would suggest a time limit of 7 days maybe and allow users to delete their own messages. Else they will edit it anyways and just remove everything. Sometimes you write bullshit or stuff that you should not share and then it's perfectly fine to delete your message.

**Comment by ivirshup** [comment]
> > Should we have separate streams for docs and CI, or are those both “repo management”
>
> I'd not create separate streams for those. They should be handled by the respective package.

I fee like these are also a topic of discussion though. Doc styling, sphinx plugins, and "why is sphinx breaking oh god i just want to make a bug fix release"  are topics it's useful to talk to each other about.

### Email visibility

So the setting is "visible to who", which I've currently set to admins and mods. [It's is actually even weirder than that](https://scverse.zulipchat.com/help/restrict-visibility-of-email-addresses), since it'll show a fake non-functional email address sometimes.

We can add an optional field for email addresses. I've added these for github and twitter:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/8238804/154045359-0ce17bc8-dfac-4c6f-a8d0-a6777f67326a.png">

**Comment by grst** [comment]
> I fee like these are also a topic of discussion though. Doc styling, sphinx plugins, and "why is sphinx breaking oh god i just want to make a bug fix release" are topics it's useful to talk to each other about.

I agree, but I'd go for a single stream for now. Zulip still has topics for substructure, and it's not like we couldn't change that later if necessary. 

> General
> Announce (is this mod only?)

What would be the purpose of the General channel? Can everyone post there and can one unsubscribe?
In the nf-core slack, they ended up renaming "General" into "Announcements" because "General" kept being abused for help-requests which should have gone somewhere else.

**Comment by ivirshup** [comment]
> What would be the purpose of the General channel? Can everyone post there and can one unsubscribe?

I think "on the topic of scverse, but doesn't fit anywhere else miscellaneous"

**Comment by ivirshup** [comment]
> I agree, but I'd go for a single stream for now.

Single stream for these topics or these just falling under general?

**Comment by grst** [comment]
> Single stream for these topics or these just falling under general?
> To clarify, I was arguing that there should be a stream for this kind of thing, but not per project.

I think a stream "repo managment" for both of them (as you suggested) makes sense.

**Comment by Zethson** [comment]
> > What would be the purpose of the General channel? Can everyone post there and can one unsubscribe?
> 
> I think "on the topic of scverse, but doesn't fit anywhere else"

Sure, but as @grst mentioned, people also tend to abuse this to be lazy and to not find the appropriate channel to post. But we can easily change this as we go. It's not difficult :)

**Comment by ivirshup** [comment]
Thoughts on having a "help" stream?

**Comment by Zethson** [comment]
> Thoughts on having a "help" stream?

Tricky. I think that we want to keep help requests away from Zulip and rather have them asked on Discourse, right? I suspect that we would constantly have to point this out if a "help" stream existed.
