### ISSUE TITLE
Automatically close stale issues

### ISSUE THREAD

**Issue by Zethson** [scverse/governance#41]
- [ ] Additional function parameters / changed functionality / changed defaults?
- [ ] New analysis tool: A simple analysis tool you have been using and are missing in `sc.tools`?
- [ ] New plotting function: A kind of plot you would like to seein `sc.pl`?
- [ ] External tools: Do you know an existing package that should go into `sc.external.*`?
- [X] Other?

Scanpy gets quite a lot of issues, which is per se a good thing. However, some of them get old, forgotten and stay without response.
We should close them automatically after a set amount of time. 3 months is quite common.
The issue then gets closed by a bot and it can be reopened automatically by writing anything in the issue under it.

I would propose to start with 6 months and if things get out of hand we can still change it to 3 or 12 months or something.

CC @giovp

**Comment by grst** [comment]
follow-up: 
https://github.com/scverse/anndata/pull/818
