### ISSUE TITLE
Adding: Anna Schaar

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#51]
# Onboarding checklist

- [x] add to website
- [x] add to core-team@scverse.org
- [x] add to zulip
  - [x] add to core stream
  - [x] add to core group
- [x] add to github org and [scverse/core](https://github.com/orgs/scverse/teams/core) github team
- [x] invite to governance and community meetings
- [x] add to google drive
- [x] write permission on google calendar
- [x] announce the new member on twitter
- [ ] add to password manager
- [ ] moderation privileges on discourse

**Comment by Zethson** [comment]
@ivirshup I see 2 unticked boxes. Would it be possible for you to please take care of them so that the onboarding process is finished for Anna, please?
