### ISSUE TITLE
Adding: Philipp Angerer

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#54]
# Onboarding checklist

- [x] add to website
- [x] add to core-team@scverse.org
- [x] invite to governance and community meetings
- [x] write permission on google calendar
- [x] add to google drive
- [x] add to zulip
  - [x] add to core stream
  - [x] add to core group
- [x] moderation privileges on discourse
- [x] add to password manager
- [x] add to github org and [scverse/core](https://github.com/orgs/scverse/teams/core) github team
- ~~[ ] announce the new member on twitter~~

**Comment by flying-sheep** [comment]
>  add to website

seems like that’s done: https://scverse.org/people/

> invite to governance and community meetings

you sent me a calendar invite, so done too

**Comment by flying-sheep** [comment]
Actually, scratch mentioning me on Twitter, that platform is too much of a train wreck. I just deleted my account.

I don't want to be on a platform whose owner uses it to promote misogyny and white supremacists.
