### ISSUE TITLE
Adding: Ilan Gold

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#65]
# Onboarding checklist

Welcome @ilan-gold!

- [ ] add to website
- [ ] add to core_team@scverse.org google group. Note: the email address used here will also get access to the shared google drive and calendars.
- [x] add to zulip
    - [x] @core team
    - [x] core-team private channel
- [x] Grant "Leader" trust level on discourse
- [x] add to password manager
- [x] add to github org and [scverse/core](https://github.com/orgs/scverse/teams/core) github team
- [ ] announce the new member on twitter

**Comment by Zethson** [comment]
Duplicated now with #70
