### ISSUE TITLE
Adding: Tim Treis

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/governance#69]
# Onboarding checklist

- [x] add to website
- [x] add to core@scverse.org google group. Note: the email address used here will also get access to the shared google drive and calendars (see [here](https://docs.google.com/document/d/1VbmcPM5pivthVnDHH0UgX7zITQFIJyahDjI_WYu7xzE/edit#heading=h.rjvd7yl35x9c))
- [x] add to zulip
    - [x] @core team
    - [x] core-team private channel (see [here](https://docs.google.com/document/d/1VbmcPM5pivthVnDHH0UgX7zITQFIJyahDjI_WYu7xzE/edit#heading=h.6idmmugj38ay))
- [x] add to github org and [scverse/core](https://github.com/orgs/scverse/teams/core) github team
- [x] Send them link to [core team handbook](https://docs.google.com/document/d/1VbmcPM5pivthVnDHH0UgX7zITQFIJyahDjI_WYu7xzE/edit?usp=sharing)
- [x] add to password manager
- [ ] Add to NumFOCUS slack
- [ ] announce the new member on twitter
- [ ] Grant "Leader" trust level on discourse

Welcome @timtreis!

**Comment by timtreis** [comment]
- @Zethson just added me to NumFOCUS
- Don't really care about Twitter
