### ISSUE TITLE
Adding: Severin Dicks

### ISSUE THREAD

**Issue by grst** [scverse/governance#72]
# Onboarding checklist

Welcome @Intron7! 

- [x] add to [website core team member list](https://github.com/scverse/scverse.github.io/blob/main/content/people/_index.md)
- [x] add to core@scverse.org [google group](https://groups.google.com/u/1/g/scverse-core-team). Note: the email address used here will also get access to the shared google drive and calendars (see [core team handbook][])
- [x] add to zulip
    - [x] [zulip core group](https://scverse.zulipchat.com/#groups/308955/core/members)
    - [x] [core team private channel](https://docs.google.com/document/d/1VbmcPM5pivthVnDHH0UgX7zITQFIJyahDjI_WYu7xzE/edit#heading=h.6idmmugj38ay)
- [x] Grant “[Leader](https://discourse.scverse.org/badges/4/leader)” trust level on discourse
- [ ] add to [password manager](https://scverse.1password.com/)
- [x] add to github org and [scverse/core](https://github.com/orgs/scverse/teams/core) github team
- [x] Add to [NumFOCUS slack](https://numfocus.slack.com/)
- [x] Send them link to [core team handbook][]
- [ ] announce the new member on [scverse_team twitter](https://twitter.com/scverse_team/)

[core team handbook](https://docs.google.com/document/d/1VbmcPM5pivthVnDHH0UgX7zITQFIJyahDjI_WYu7xzE/edit)

**Comment by grst** [comment]
@mikelkou, do we still announce core team members? Could I again leave this to you please?

**Comment by mikelkou** [comment]
I will make an announcement for all of our new members then, since I didn't do it so for anyone individually the last semester. Sorry about that.
