### ISSUE TITLE
Discussion Channels

### ISSUE THREAD

**Issue by ivirshup** [scverse/governance#9]
We should figure out what the discussion channels are.

Current ideas are:

- [ ] One chat app
- [ ] One asynchronous app

At our next scverse meeting we will be looking at proposals for a chat app.

Current plan is to re-arrange the scanpy discourse to be scverse wide.

**Comment by adamgayoso** [comment]
what about gitter for org chat?

**Comment by ivirshup** [comment]
I don't really like gitter. The search is bad, there's only one stream, and there's no private messages.

We use those features in slack a lot among the dev team, and I wouldn't want to lose them by moving to gitter. I also don't think having multiple chat apps is a good idea.

Also, have we had this discussion before? I have deja vu

**Comment by ivirshup** [comment]
Ahh, you've raised it (https://github.com/theislab/scanpy/issues/1716), but I think I ended up talking through it elsewhere... oops

**Comment by adamgayoso** [comment]
> I don't really like gitter. The search is bad, there's only one stream, and there's no private messages.

There are threads and private messages, you can also create multiple rooms (equivalent of slack channels) in the same community

The search is also fine

**Comment by adamgayoso** [comment]
If you want to try ours (not heavily utilized), here's the [invite link](https://gitter.im/scvi-tools/quick-help?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by ivirshup** [comment]
It's very possible it's gotten better since I've used it much. Could you write up what you see as the pros/ cons as and maybe link to some docs about it?

I do think a more powerful chat app is particularly useful the larger the size of the community. Maybe the compatibility with element can do that for gitter?

I don't think the interface has improved a ton, some things I learned:

* You leave a channel via the settings menu
  * This may rearrange your channel lists and maybe also make you leave other channels too? (leaving conda-forge also removed scvi-tools I think?)
* Clicking the channel name takes you to a github repositrory

**Comment by adamgayoso** [comment]
Gitter

**Pros**

- Free
- Channels (rooms)
- Threads
- Decent search
- Private messaging
- Can be accessed from Element
- Latex, github-flavored markdown
- Integrations with github, discourse
- Gitter desktop/mobile apps
- Simplicity means it's not ideal for more involved discussion such as Q+A (leave to discourse)

**Cons**

- A little less snappy and intuitive than slack
- Slack search better


> Clicking the channel name takes you to a github repositrory

This is only because I associated that room with a github repo, this is optional

**Comment by ivirshup** [comment]
Looking into gitter made me realize we might have some requirements we didn't really need to consider for smaller group sizes. In particular moderation. What kind of moderation tools are requirements for a chat app?

Possibilities:

* Bans?
* Temporary or channel specific bans?
* "moderator" role?
* Auto-moderation tools?

**Comment by gtca** [comment]
For the chat app, I think it's also important to consider it's not only the developers who are going to use it. In fact, we expect majority people there not to be developers. Hence user-friendliness, familiarity and moderation capabilities might be more important than for a developers-focused chat.

**Comment by adamgayoso** [comment]
> For the chat app, I think it's also important to consider it's not only the developers who are going to use it. In fact, we expect most people there not to be developers. Hence user-friendliness, familiarity and moderation capabilities might be more important than for a developers-focused chat.

Not sure this has to be the case, see https://github.com/scverse/governance/issues/14#issuecomment-1030204714

**Comment by Zethson** [comment]
> Probably can close this issue as soon as we get a new staging issue for zulip @ivirshup

That's the case now, right? Feel free to reopen!
